-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 23:11:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BatalhaDeRima
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BatalhaDeRima
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BatalhaDeRima` DEFAULT CHARACTER SET utf8 ;
USE `BatalhaDeRima` ;

-- -----------------------------------------------------
-- Table `BatalhaDeRima`.`Batalha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BatalhaDeRima`.`Batalha` (
  `nome` VARCHAR(45) NOT NULL,
  `diaDaSemana` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BatalhaDeRima`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BatalhaDeRima`.`Participante` (
  `idParticipante` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` VARCHAR(45) NOT NULL,
  `vulgo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParticipante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BatalhaDeRima`.`Vencedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BatalhaDeRima`.`Vencedores` (
  `idVencedores` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `vulgo` VARCHAR(45) NOT NULL,
  `edicao` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NULL,
  PRIMARY KEY (`idVencedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BatalhaDeRima`.`Edicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BatalhaDeRima`.`Edicao` (
  `Batalha_nome` VARCHAR(45) NOT NULL,
  `Participante_idParticipante` INT NOT NULL,
  `numEdicao` INT NOT NULL,
  `Vencedores_idVencedores` INT NOT NULL,
  PRIMARY KEY (`Batalha_nome`, `Participante_idParticipante`, `Vencedores_idVencedores`),
  INDEX `fk_Batalha_has_Participante_Participante1_idx` (`Participante_idParticipante` ASC) VISIBLE,
  INDEX `fk_Batalha_has_Participante_Batalha_idx` (`Batalha_nome` ASC) VISIBLE,
  INDEX `fk_Edicao_Vencedores1_idx` (`Vencedores_idVencedores` ASC) VISIBLE,
  CONSTRAINT `fk_Batalha_has_Participante_Batalha`
    FOREIGN KEY (`Batalha_nome`)
    REFERENCES `BatalhaDeRima`.`Batalha` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Batalha_has_Participante_Participante1`
    FOREIGN KEY (`Participante_idParticipante`)
    REFERENCES `BatalhaDeRima`.`Participante` (`idParticipante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Edicao_Vencedores1`
    FOREIGN KEY (`Vencedores_idVencedores`)
    REFERENCES `BatalhaDeRima`.`Vencedores` (`idVencedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
